version: '3'

services:

    webexpe:
        container_name: webexpeinstance
        image: djangowebexpe
        restart: always
        volumes:
            - "./media:/usr/src/app/media" # get access to media files
        ports:
           - "${PORT:-8000}:8000"