# Generated by Django 3.2.12 on 2022-02-05 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('javascripts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/first_example.js', 'experiment/js/first_example.js')], max_length=30, null=True)),
                ('styles', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/example.css', 'experiment/css/example.css')], max_length=26, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('template', models.CharField(choices=[], help_text='You can add templates into: expe/templates/end', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamplePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('javascripts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/first_example.js', 'experiment/js/first_example.js')], max_length=30, null=True)),
                ('styles', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/example.css', 'experiment/css/example.css')], max_length=26, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('template', models.CharField(choices=[('examples/first_example.html', 'examples/first_example.html')], help_text='You can add templates into: examples/first_example.html', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('estimated_duration', models.DurationField(default=datetime.timedelta(0), help_text='hh:mm:ss')),
                ('slug', models.SlugField(blank=True, help_text='This field is not required and will be generated automatically when the object is saved based on the title of the experiment', max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('end_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='expe.endpage')),
                ('example_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='expe.examplepage')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('javascripts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/first_example.js', 'experiment/js/first_example.js')], max_length=30, null=True)),
                ('styles', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/example.css', 'experiment/css/example.css')], max_length=26, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('template', models.CharField(choices=[], help_text='You can add templates into: expe/templates/information', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('javascripts', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/first_example.js', 'experiment/js/first_example.js')], max_length=30, null=True)),
                ('styles', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/example.css', 'experiment/css/example.css')], max_length=26, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('template', models.CharField(choices=[], help_text='You can add templates into: expe/templates/main', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Session will be displayed but not accessible', null=True)),
                ('is_available', models.IntegerField(blank=True, choices=[(1, 'Available'), (0, 'Disabled')], default=1, help_text='Session will not be displayed if disabled', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='expe.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='UserExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sessions', models.ManyToManyField(null=True, related_name='users', to='expe.Session')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('binary', models.BinaryField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='expe.experimentprogress')),
            ],
        ),
        migrations.AddField(
            model_name='experimentprogress',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='expe.session'),
        ),
        migrations.AddField(
            model_name='experimentprogress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='expe.userexperiment'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='information_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='expe.informationpage'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='main_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='expe.mainpage'),
        ),
    ]
