# Generated by Django 3.2.12 on 2022-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalexperimentprogress',
            name='is_finished',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
