# Generated by Django 3.2.12 on 2022-02-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0002_classicalexperimentprogress_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicalexperimentprogress',
            name='is_finished',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
