# Generated by Django 3.2.12 on 2022-02-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0003_alter_classicalexperimentprogress_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicalexperimentprogress',
            name='is_started',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
