# Generated by Django 3.2.12 on 2022-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0003_alter_experiment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='experiment',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
    ]
