# Generated by Django 3.2.12 on 2022-02-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0004_classicalexperimentprogress_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicalexperimentprogress',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
