# Generated by Django 3.2.12 on 2022-02-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0005_rename_slug_experiment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='experiment',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='url',
            field=models.SlugField(blank=True, help_text='This field is not required and will be generated automatically when the object is saved based on the title of the experiment', max_length=255, unique=True),
        ),
    ]
