# Generated by Django 3.2.12 on 2022-02-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0006_auto_20220204_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepage',
            name='template',
            field=models.CharField(choices=[('templates/examples/first_example.html', 'templates/examples/first_example.html')], help_text='You can add templates into: expe/templates/examples', max_length=255),
        ),
    ]
