# Generated by Django 3.2.12 on 2022-02-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0006_auto_20220203_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('javascript', models.CharField(max_length=255)),
                ('config', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('template', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='userexperiment',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='userexperiment',
            name='experiment',
        ),
        migrations.AddField(
            model_name='session',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expe.experiment'),
        ),
        migrations.AddField(
            model_name='userexperiment',
            name='sessions',
            field=models.ManyToManyField(to='expe.Session'),
        ),
    ]
