# Generated by Django 3.2.12 on 2022-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0008_experiment_example_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperiment',
            name='sessions',
            field=models.ManyToManyField(null=True, to='expe.Session'),
        ),
    ]
