# Generated by Django 3.2.12 on 2022-02-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0008_alter_examplepage_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
