# Generated by Django 3.2.12 on 2022-02-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0008_alter_classicalexperimentprogress_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicalexperimentprogress',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
