# Generated by Django 3.2.12 on 2022-02-04 15:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0009_alter_examplepage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepage',
            name='javascripts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/first_example.js', 'experiment/js/first_example.js')], max_length=30, null=True),
        ),
    ]
