# Generated by Django 3.2.12 on 2022-02-06 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0010_alter_classicalexperimentprogress_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='estimated_duration',
        ),
        migrations.AddField(
            model_name='experimentsession',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentsession',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='hh:mm:ss'),
        ),
    ]
