# Generated by Django 3.2.12 on 2022-02-03 16:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0010_auto_20220203_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplepage',
            name='javascript',
        ),
        migrations.AddField(
            model_name='examplepage',
            name='javascripts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FileSaver.js', 'FileSaver.js'), ('keyEvents.js', 'keyEvents.js'), ('loadImg.js', 'loadImg.js'), ('results.js', 'results.js'), ('updateData.js', 'updateData.js')], max_length=61, null=True),
        ),
        migrations.AddField(
            model_name='examplepage',
            name='styles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('expe.css', 'expe.css')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='config',
            field=models.JSONField(null=True),
        ),
    ]
