# Generated by Django 3.2.12 on 2022-02-06 07:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0011_auto_20220206_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentstep',
            old_name='datetime',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='endpage',
            name='javascripts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/classical_main.js', 'experiment/js/classical_main.js')], max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='endpage',
            name='styles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/classical_main.css', 'experiment/css/classical_main.css'), ('experiment/css/hide_sidebar.css', 'experiment/css/hide_sidebar.css')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='javascripts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/classical_main.js', 'experiment/js/classical_main.js')], max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='styles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/classical_main.css', 'experiment/css/classical_main.css'), ('experiment/css/hide_sidebar.css', 'experiment/css/hide_sidebar.css')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='javascripts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/classical_main.js', 'experiment/js/classical_main.js')], max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='styles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/classical_main.css', 'experiment/css/classical_main.css'), ('experiment/css/hide_sidebar.css', 'experiment/css/hide_sidebar.css')], max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='javascripts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/js/classical_main.js', 'experiment/js/classical_main.js')], max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='styles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('experiment/css/classical_main.css', 'experiment/css/classical_main.css'), ('experiment/css/hide_sidebar.css', 'experiment/css/hide_sidebar.css')], max_length=65, null=True),
        ),
    ]
