# Generated by Django 3.2.12 on 2022-02-03 17:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0011_auto_20220203_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepage',
            name='javascripts',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('example.js', 'example.js')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='styles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('example.css', 'example.css')], max_length=11, null=True),
        ),
    ]
