# Generated by Django 3.2.12 on 2022-02-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0012_auto_20220206_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperiment',
            name='sessions',
        ),
        migrations.AlterField(
            model_name='classicalexperimentprogress',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progresses', to='expe.experimentsession'),
        ),
        migrations.AlterField(
            model_name='classicalexperimentprogress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progresses', to='expe.userexperiment'),
        ),
    ]
