# Generated by Django 3.2.12 on 2022-02-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0012_auto_20220203_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='example_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='expe.examplepage'),
        ),
        migrations.AlterField(
            model_name='session',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='expe.experiment'),
        ),
    ]
