# Generated by Django 3.2.12 on 2022-02-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expe', '0014_auto_20220206_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='experiment',
            name='is_available',
            field=models.IntegerField(blank=True, choices=[(1, 'Available'), (0, 'Disabled')], default=1, null=True),
        ),
    ]
